# Generated by Django 4.2.6 on 2023-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('shop_code', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=25)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=25)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=25)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
    ]
